module.exports = {
  Sheets:{
    Sheet1:{
      '!ref': 'A1:Z7',
      A1: {
        t: 's',
        v: 'Create new bank account',
        r: '<t>Create new bank account</t>',
        h: 'Create new bank account',
        w: 'Create new bank account',
      },
      A2: {
        t: 's',
        v: 'module_under_test.js',
        r: '<t>module_under_test.js</t>',
        h: 'module_under_test.js',
        w: 'module_under_test.js',
        l: {
          ref: 'A2',
          id: 'rId1',
          display: 'module_under_test.js',
          Target: 'http://module_under_test.js/',
          Rel: [Object],
        },
      },
      A3: {
        t: 's',
        v: 'account',
        r: '<t>account</t>',
        h: 'account',
        w: 'account',
      },
      B3: {
        t: 's',
        v: 'create',
        r: '<t>create</t>',
        h: 'create',
        w: 'create',
      },
      C3: {
        t: 's',
        v: '{\n  bankNumber: \'90090042\',\n  loginId: \'figo\',\n  customId: \'\',\n  customId2: \'\',\n  pin: \'figo\',\n  savePIN: false,\n  salt: \'secret\',\n  credentialIds: [\n    {\n      credentialId: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n      salt: \'secret\'\n    }\n  ]\n}',
        r: '<t>{\n  bankNumber: &apos;90090042&apos;,\n  loginId: &apos;figo&apos;,\n  customId: &apos;&apos;,\n  customId2: &apos;&apos;,\n  pin: &apos;figo&apos;,\n  savePIN: false,\n  salt: &apos;secret&apos;,\n  credentialIds: [\n    {\n      credentialId: &apos;5931c237-8dbc-45ac-afc3-0b5088a1ff3f&apos;,\n      salt: &apos;secret&apos;\n    }\n  ]\n}</t>',
        h: '{\n  bankNumber: \'90090042\',\n  loginId: \'figo\',\n  customId: \'\',\n  customId2: \'\',\n  pin: \'figo\',\n  savePIN: false,\n  salt: \'secret\',\n  credentialIds: [\n    {\n      credentialId: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n      salt: \'secret\'\n    }\n  ]\n}',
        w: '{\n  bankNumber: \'90090042\',\n  loginId: \'figo\',\n  customId: \'\',\n  customId2: \'\',\n  pin: \'figo\',\n  savePIN: false,\n  salt: \'secret\',\n  credentialIds: [\n    {\n      credentialId: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n      salt: \'secret\'\n    }\n  ]\n}',
      },
      E3: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      F3: {
        t: 's',
        v: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
        r: '<t>{\n  status: 201,\n  data: {\n    credential: &apos;5931c237-8dbc-45ac-afc3-0b5088a1ff3f&apos;,\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: &apos;&apos;,\n        acctName: &apos;Girokonto&apos;,\n        isSEPA: true,\n        iban: &apos;DE67900900424711951500&apos;,\n        holderName: &apos;figo&apos;,\n        currencyCode: &apos;EUR&apos;,\n        acctNo: &apos;4711951500&apos;,\n        fromUPD: false,\n        allowedSegTypes: [ &apos;HKUEB&apos;, &apos;HKUMB&apos; ],\n        custID: &apos;&apos;,\n        bic: &apos;DEMODE01&apos;,\n        bankName: &apos;Demobank&apos;,\n        icon: &apos;demokonto.png&apos;,\n        acctType: 1,\n        countryCode: &apos;280&apos;,\n        bankCode: &apos;90090042&apos; },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: &apos;&apos;,\n        acctName: &apos;Sparkonto&apos;,\n        isSEPA: true,\n        iban: &apos;DE05900900424711951501&apos;,\n        holderName: &apos;figo&apos;,\n        currencyCode: &apos;EUR&apos;,\n        acctNo: &apos;4711951501&apos;,\n        fromUPD: false,\n        allowedSegTypes: [ &apos;HKUMB&apos;],\n        custID: &apos;&apos;,\n        bic: &apos;DEMODE01&apos;,\n        bankName: &apos;Demobank&apos;,\n        icon: &apos;demokonto.png&apos;,\n        acctType: 10,\n        countryCode: &apos;280&apos;,\n        bankCode: &apos;90090042&apos; }\n    ]\n  }\n}</t>',
        h: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
        w: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}', },
      A4: {
        t: 's',
        v: 'object_under_test',
        r: '<t>object_under_test</t>',
        h: 'object_under_test',
        w: 'object_under_test',
      },
      B4: {
        t: 's',
        v: 'method2',
        r: '<t>method2</t>',
        h: 'method2',
        w: 'method2',
      },
      C4: {
        t: 's',
        v: 'input1',
        r: '<t>input1</t>',
        h: 'input1',
        w: 'input1',
      },
      D4: {
        t: 's',
        v: 'input2',
        r: '<t>input2</t>',
        h: 'input2',
        w: 'input2',
      },
      E4: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      F4: {
        t: 's',
        v: 'output1',
        r: '<t>output1</t>',
        h: 'output1',
        w: 'output1',
      },
      A5: {
        t: 's',
        v: 'object_under_test',
        r: '<t>object_under_test</t>',
        h: 'object_under_test',
        w: 'object_under_test',
      },
      B5: {
        t: 's',
        v: 'method3',
        r: '<t>method3</t>',
        h: 'method3',
        w: 'method3',
      },
      C5: { t: 's', v: 'input1', f: 'C4', h: 'input1', w: 'input1' },
      D5: { t: 'n', v: 2, w: '2' },
      E5: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      F5: { t: 'b', v: true, w: 'TRUE' },
      A6: {
        t: 's',
        v: 'object_under_stringRef',
        r: '<t>object_under_stringRef</t>',
        h: 'object_under_stringRef',
        w: 'object_under_stringRef',
      },
      B6: {
        t: 's',
        v: 'balance',
        r: '<t>balance</t>',
        h: 'balance',
        w: 'balance',
      },
      C6: { t: 's', v: 'input1', f: 'C5', h: 'input1', w: 'input1' },
      E6: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      F6: { t: 'b', v: true, w: 'TRUE' },
      A7: {
        t: 's',
        v: 'object_under_test_funcRef',
        r: '<t>object_under_test_funcRef</t>',
        h: 'object_under_test_funcRef',
        w: 'object_under_test_funcRef',
      },
      B7: {
        t: 's',
        v: 'balance',
        r: '<t>balance</t>',
        h: 'balance',
        w: 'balance',
      },
      C7: {
        t: 's',
        v: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
        f: 'F3',
        h: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
      w: '{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}', },
      E7: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      F7: { t: 'b', v: false, w: 'FALSE' },
    },
  },
  invocationCells: ['E3', 'E4', 'E5', 'E6', 'E7'],
  objectsUnderTest: ['A3', 'A4', 'A5', 'A6', 'A7'],
  methodsUnderTest: ['B3', 'B4', 'B5', 'B6', 'B7'],
  inputs:  ['C3', 'C4', 'C5', 'C6', 'C7', 'D4', 'D5'],
  outputs: ['F3', 'F4', 'F5', 'F6', 'F7'],
  basicScheme: {
    description: 'Create new bank account',
    moduleUnderTest: 'module_under_test.js',
    objectsUnderTest: ['A3', 'A4', 'A5', 'A6', 'A7'],
    methodsUnderTest: ['B3', 'B4', 'B5', 'B6', 'B7'],
    inputs: ['C3', 'C4', 'D4', 'C5', 'D5', 'C6', 'C7'],
    outputs: ['F3', 'F4', 'F5', 'F6', 'F7'],
    invocations: ['E3', 'E4', 'E5', 'E6', 'E7'],
  },
  transformedScheme: {
    1: 'Create new bank account',
    2: 'module_under_test.js',
    3: {
      objectsUnderTest: ['A3'],
      methodsUnderTest: ['B3'],
      inputs: ['C3'],
      outputs: ['F3'],
      invocations: ['E3'],
    },
    4: {
      objectsUnderTest: ['A4'],
      methodsUnderTest: ['B4'],
      inputs: ['C4', 'D4'],
      outputs: ['F4'],
      invocations: ['E4'],
    },
    5: {
      objectsUnderTest: ['A5'],
      methodsUnderTest: ['B5'],
      inputs: ['C5', 'D5'],
      outputs: ['F5'],
      invocations: ['E5'],
    },
    6: {
      objectsUnderTest: ['A6'],
      methodsUnderTest: ['B6'],
      inputs: ['C6'],
      outputs: ['F6'],
      invocations: ['E6'],
    },
    7: {
      objectsUnderTest: ['A7'],
      methodsUnderTest: ['B7'],
      inputs: ['C7'],
      outputs: ['F7'],
      invocations: ['E7'],
    },
  },
  transformedSchemeCallsOnly: [
    {
      objectsUnderTest: ['A3'],
      methodsUnderTest: ['B3'],
      inputs: ['C3'],
      outputs: ['F3'],
      invocations: ['E3'],
    },
    {
      objectsUnderTest: ['A4'],
      methodsUnderTest: ['B4'],
      inputs: ['C4', 'D4'],
      outputs: ['F4'],
      invocations: ['E4'],
    },
    {
      objectsUnderTest: ['A5'],
      methodsUnderTest: ['B5'],
      inputs: ['C5', 'D5'],
      outputs: ['F5'],
      invocations: ['E5'],
    },
    {
      objectsUnderTest: ['A6'],
      methodsUnderTest: ['B6'],
      inputs: ['C6'],
      outputs: ['F6'],
      invocations: ['E6'],
    },
    {
      objectsUnderTest: ['A7'],
      methodsUnderTest: ['B7'],
      inputs: ['C7'],
      outputs: ['F7'],
      invocations: ['E7'],
    },
  ],
  thirdRow: {
    objectUnderTest: 'account',
    methodUnderTest: 'create',
    inputs: ['{\n  bankNumber: \'90090042\',\n  loginId: \'figo\',\n  customId: \'\',\n  customId2: \'\',\n  pin: \'figo\',\n  savePIN: false,\n  salt: \'secret\',\n  credentialIds: [\n    {\n      credentialId: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n      salt: \'secret\'\n    }\n  ]\n}'],
    outputs: ['{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
     'output2'],
  },
  refScheme: {
    cells: [
      'A1',
      'A2',
      'A3',
      'B3',
      'C3',
      'E3',
      'A4',
      'B4',
      'D4',
      'E4',
      'F4',
      'A5',
      'B5',
      'D5',
      'E5',
      'F5',
      'A6',
      'B6',
      'E6',
      'F6',
      'A7',
      'B7',
      'E7',
      'F7',
    ],
    icells: ['C4', 'F3'],
    ocells: ['C6', 'C7'],
    iocells: ['C5'],
  },
};
