module.exports = {
  Sheets:{
    Sheet1:{
      '!ref': 'A1:G5',
      A1:
       { t: 's',
         v: 'Test for tranlation to js file',
         r: '<t>Test for tranlation to js file</t>',
         h: 'Test for tranlation to js file',
         w: 'Test for tranlation to js file' },
      A2:
       { t: 's',
         v: 'BankAustria',
         r: '<t>BankAustria</t>',
         h: 'BankAustria',
         w: 'BankAustria' },
      A3:
       { t: 's',
         v: 'BankAustria',
         r: '<t>BankAustria</t>',
         h: 'BankAustria',
         w: 'BankAustria' },
      B3:
       { t: 's',
         v: 'getAccounts',
         r: '<t>getAccounts</t>',
         h: 'getAccounts',
         w: 'getAccounts' },
      C3:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         r: '<t> {  &quot;countryCode&quot;: &quot;280&quot;,&#10;    &quot;custID&quot;: &quot;&quot;,&#10;    &quot;custID2&quot;: &quot;&quot;,&#10;    &quot;hbciVersion&quot;: &quot;0&quot;,&#10;    &quot;language&quot;: 1,&#10;    &quot;url&quot;: &quot;bawagPSK.js&quot;,&#10;    &quot;userID&quot;: &quot;64769092&quot;,&#10;    &quot;pin&quot;: &quot;38567&quot; }</t>',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' },
      D3:
       { t: 's',
         v: '“38567”',
         r: '<t>â38567â</t>',
         h: '“38567”',
         w: '“38567”' },
      E3:
       { t: 's',
         v: '”12345”',
         r: '<t>â12345â</t>',
         h: '”12345”',
         w: '”12345”' },
      F3: { t: 's', v: '||', r: '<t>||</t>', h: '||', w: '||' },
      G3:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         r: '<t> {  &quot;countryCode&quot;: &quot;280&quot;,&#10;    &quot;custID&quot;: &quot;&quot;,&#10;    &quot;custID2&quot;: &quot;&quot;,&#10;    &quot;hbciVersion&quot;: &quot;0&quot;,&#10;    &quot;language&quot;: 1,&#10;    &quot;url&quot;: &quot;bawagPSK.js&quot;,&#10;    &quot;userID&quot;: &quot;64769092&quot;,&#10;    &quot;pin&quot;: &quot;38567&quot; }</t>',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' },
      A4:
       { t: 's',
         v: 'BankAustria',
         r: '<t>BankAustria</t>',
         h: 'BankAustria',
         w: 'BankAustria' },
      B4:
       { t: 's',
         v: 'getAccounts',
         r: '<t>getAccounts</t>',
         h: 'getAccounts',
         w: 'getAccounts' },
      C4:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         f: 'C3',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' },
      F4: { t: 's', v: '|', r: '<t>|</t>', h: '|', w: '|' },
      G4:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         r: '<t> {  &quot;countryCode&quot;: &quot;280&quot;,&#10;    &quot;custID&quot;: &quot;&quot;,&#10;    &quot;custID2&quot;: &quot;&quot;,&#10;    &quot;hbciVersion&quot;: &quot;0&quot;,&#10;    &quot;language&quot;: 1,&#10;    &quot;url&quot;: &quot;bawagPSK.js&quot;,&#10;    &quot;userID&quot;: &quot;64769092&quot;,&#10;    &quot;pin&quot;: &quot;38567&quot; }</t>',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' },
      A5:
       { t: 's',
         v: 'BankAustria',
         r: '<t>BankAustria</t>',
         h: 'BankAustria',
         w: 'BankAustria' },
      B5:
       { t: 's',
         v: 'getAccounts',
         r: '<t>getAccounts</t>',
         h: 'getAccounts',
         w: 'getAccounts' },
      C5:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         f: 'C4',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' },
      D5:
       { t: 's',
         v: '“38567”',
         r: '<t>â38567â</t>',
         h: '“38567”',
         w: '“38567”' },
      F5: { t: 's', v: '||', r: '<t>||</t>', h: '||', w: '||' },
      G5:
       { t: 's',
         v: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         r: '<t> {  &quot;countryCode&quot;: &quot;280&quot;,&#10;    &quot;custID&quot;: &quot;&quot;,&#10;    &quot;custID2&quot;: &quot;&quot;,&#10;    &quot;hbciVersion&quot;: &quot;0&quot;,&#10;    &quot;language&quot;: 1,&#10;    &quot;url&quot;: &quot;bawagPSK.js&quot;,&#10;    &quot;userID&quot;: &quot;64769092&quot;,&#10;    &quot;pin&quot;: &quot;38567&quot; }</t>',
         h: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }',
         w: ' {  "countryCode": "280",&#10;    "custID": "",&#10;    "custID2": "",&#10;    "hbciVersion": "0",&#10;    "language": 1,&#10;    "url": "bawagPSK.js",&#10;    "userID": "64769092",&#10;    "pin": "38567" }' }
    }
  },
  invocationCells: ['F3', 'F4', 'F5'],
  objectsUnderTest:['A3', 'A4', 'A5'],
  methodsUnderTest: ['B3', 'B4', 'B5', 'B6', 'B7'],
  inputs:  ['C3', 'D3', 'E3', 'C4', 'C5', 'D5'],
  outputs: ['G3', 'G4', 'G5'],
  basicScheme: {
    description: 'Test for tranlation to js file',
    moduleUnderTest: 'BankAustria',
    objectsUnderTest:['A3', 'A4', 'A5'],
    methodsUnderTest: ['B3', 'B4', 'B5'],
    inputs: ['C3', 'D3', 'E3', 'C4', 'C5', 'D5'],
    outputs: ['G3', 'G4', 'G5'],
    invocations: ['F3', 'F4', 'F5'],
  },
  transformedScheme: {
    1: 'Test for tranlation to js file',
    2: 'BankAustria',
    3: {
      objectsUnderTest: ['A3'],
      methodsUnderTest: ['B3'],
      inputs: ['C3', 'D3', 'E3'],
      outputs: ['G3'],
      invocations: ['F3'],
    },
    4: {
      objectsUnderTest: ['A4'],
      methodsUnderTest: ['B4'],
      inputs: ['C4'],
      outputs: ['G4'],
      invocations: ['F4'],
    },
    5: {
      objectsUnderTest: ['A5'],
      methodsUnderTest: ['B5'],
      inputs: ['C5', 'D5'],
      outputs: ['G5'],
      invocations: ['F5'],
    },
  },
  transformedSchemeCallsOnly: [
    {
      objectsUnderTest: ['A3'],
      methodsUnderTest: ['B3'],
      inputs: ['C3', 'D3', 'E3'],
      outputs: ['G3'],
      invocations: ['F3'],
    },
    {
      objectsUnderTest: ['A4'],
      methodsUnderTest: ['B4'],
      inputs: ['C4'],
      outputs: ['G4'],
      invocations: ['F4'],
    },
    {
      objectsUnderTest: ['A5'],
      methodsUnderTest: ['B5'],
      inputs: ['C5', 'D5'],
      outputs: ['G5'],
      invocations: ['F5'],
    },
  ],
  thirdRow: {
    objectUnderTest: 'account',
    methodUnderTest: 'create',
    inputs: ['{\n  bankNumber: \'90090042\',\n  loginId: \'figo\',\n  customId: \'\',\n  customId2: \'\',\n  pin: \'figo\',\n  savePIN: false,\n  salt: \'secret\',\n  credentialIds: [\n    {\n      credentialId: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n      salt: \'secret\'\n    }\n  ]\n}'],
    outputs: ['{\n  status: 201,\n  data: {\n    credential: \'5931c237-8dbc-45ac-afc3-0b5088a1ff3f\',\n    accounts: [\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Girokonto\',\n        isSEPA: true,\n        iban: \'DE67900900424711951500\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951500\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUEB\', \'HKUMB\' ],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 1,\n        countryCode: \'280\',\n        bankCode: \'90090042\' },\n      { onlyAllowedSegTypes: true,\n        subAcctNo: \'\',\n        acctName: \'Sparkonto\',\n        isSEPA: true,\n        iban: \'DE05900900424711951501\',\n        holderName: \'figo\',\n        currencyCode: \'EUR\',\n        acctNo: \'4711951501\',\n        fromUPD: false,\n        allowedSegTypes: [ \'HKUMB\'],\n        custID: \'\',\n        bic: \'DEMODE01\',\n        bankName: \'Demobank\',\n        icon: \'demokonto.png\',\n        acctType: 10,\n        countryCode: \'280\',\n        bankCode: \'90090042\' }\n    ]\n  }\n}',
     'output2'],
  },
  refScheme: {
    cells: [
      'A1',
      'A2',
      'A3',
      'B3',
      'D3',
      'E3',
      'F3',
      'G3',
      'A4',
      'B4',
      'F4',
      'G4',
      'A5',
      'B5',
      'D5',
      'F5',
      'G5',
    ],
    icells: ['C3'],
    ocells: ['C5'],
    iocells: ['C4'],
  },
};
